pub const ACTION_CODE_MAP: &[(&str, &str)] = &[
    ("public_topic", "将此话题设为公开"),
    ("open_topic", "将此转换为话题"),
    ("private_topic", "将此话题转换为个人消息"),
    ("split_topic", "拆分了此话题"),
    ("invited_user", "邀请了用户"),
    ("invited_group", "邀请了组"),
    ("user_left", "在将自己从此消息中移除"),
    ("removed_user", "移除了用户"),
    ("removed_group", "移除了组"),
    ("autobumped", "自动提升"),
    ("autoclosed.enabled", "关闭话题"),
    ("autoclosed.disabled", "打开话题"),
    ("closed.enabled", "关闭话题"),
    ("closed.disabled", "打开话题"),
    ("archived.enabled", "归档话题"),
    ("archived.disabled", "取消归档话题"),
    ("pinned.enabled", "置顶话题"),
    ("pinned.disabled", "取消置顶话题"),
    ("pinned_globally.enabled", "全站置顶话题"),
    ("pinned_globally.disabled", "取消全站置顶话题"),
    ("visible.enabled", "公开话题"),
    ("visible.disabled", "取消公开话题"),
    (
        "banner.enabled",
        "将此设置为横幅。在用户忽略前，它将显示在每个页面的顶部。",
    ),
    (
        "banner.disabled",
        "移除了此横幅。它将不再显示在每个页面的顶部。",
    ),
];
