import { Button, HorizontalBox, VerticalBox, LineEdit, TextEdit, GridBox, CheckBox } from "std-widgets.slint";

FetchRect := VerticalBox {
    property<string> raw_topic;
    property<string> output;
    property<int> topic: 0;
    property<string> msg;
    property<int> retry-after: 5;
    property<bool> disabled;
    property<bool> anonymous;
    callback parse(string) -> int;
    callback fetch(int);
    callback browse();

    GridBox { 
        Row {
            Text { 
                horizontal-alignment: right;
                vertical-alignment: center;
                text: "水源 URL:";
            }
            LineEdit {
                text: raw_topic;
                enabled: !disabled;
                horizontal-stretch: 1;
                edited => {
                    raw-topic = self.text;
                    topic = parse(raw-topic);
                }
            }
        }
        Row {
            Text { 
                horizontal-alignment: right;
                vertical-alignment: center;
                text: "保存到:";
            }
            HorizontalLayout { 
                spacing: 8px;
                LineEdit {
                    text <=> output;
                    enabled: !disabled;
                }
                Button {
                    text: "浏览";
                    enabled: !disabled;
                    clicked => { 
                        browse();
                    }
                }
            }
        }
    }
    CheckBox {
        text: "打码用户名及头像";
        checked <=> anonymous;
        enabled: !disabled;
    }
    Text {
        vertical-stretch: 1;
        vertical-alignment: bottom;
        horizontal-alignment: center;
        color: red;
        visible: retry-after != 0;
        text: "被限流！等待 \{retry-after} 秒后重试";
    }
    Text {
        vertical-stretch: 1;
        vertical-alignment: bottom;
        horizontal-alignment: center;
        text: "\{msg}";
    }
    Button {
        text: "下载";
        enabled: !disabled && topic != 0 && output != "";
        clicked => {
            fetch(topic);
        }
    }
}

LoginRect := VerticalBox {
    property<string> token;
    property<string> err;
    property<bool> disabled: false;
    callback login();

    VerticalBox { 
        Text{
            horizontal-alignment: center;
            text: "请在自动打开的浏览器中授权登录，并粘贴授权码";
        }
        TextEdit{
            vertical-stretch: 1;
            enabled: !disabled;
            text <=> token;
        }
     }
    Text{
        horizontal-alignment: center;
        vertical-alignment: bottom;
        vertical-stretch: 1;
        color: red;
        text: err;
        visible: err != "";
    }
    Button {
        text: "登录";
        enabled: !disabled && token != "";
        clicked => {
            login();
        }
    }
}

export MainWindow := Window {
    property<string> state: "login";

    property<string> login-token;
    property<string> login-error;
    property<bool> login-disabled: false;

    property<string> fetch-msg: "等待";
    property<string> fetch-output: "";
    property<bool> fetch-disabled: false;
    property<bool> fetch-anonymous: false;
    property<int> fetch-retry-after: 0;

    callback login-cb();
    callback parse-cb(string) -> int;
    callback fetch-cb(int, string, bool);
    callback browse-cb();

    title: "水源社区存档工具";
    width: 350px;
    height: 220px;
    icon: @image-url("../platforms/icon.png");

    LoginRect {
        token <=> login-token;
        err <=> login-error;
        disabled <=> login-disabled;
        visible: state == "login";
        login => {
            login-cb();
        }
    }
    FetchRect {
        disabled <=> fetch-disabled;
        visible: state == "fetch";
        output <=> fetch-output;
        msg <=> fetch-msg;
        anonymous <=> fetch-anonymous;
        retry-after <=> fetch-retry-after;
        parse(s) => {
            parse-cb(s);
        }
        fetch(t) => {
            fetch-cb(t, fetch-output, fetch-anonymous);
        }
        browse() => {
            browse-cb();
        }
    }
}