on:
  push:
    tags:
      - 'shuiyuan-archiver/v*'

permissions:
  contents: write

name: Publish (GUI)

jobs:
  publish_gui:
    name: Publish (GUI)
    strategy:
      fail-fast: false
      matrix:
        platform: [ macos-latest, ubuntu-20.04, windows-latest ]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Setup Cargo Toolchain (Mac) 🛎️
        uses: dtolnay/rust-toolchain@stable
        if: matrix.platform == 'macos-latest'
        with:
          targets: aarch64-apple-darwin
      - name: Setup Cargo Toolchain 🛎️
        uses: dtolnay/rust-toolchain@stable
        if: matrix.platform != 'macos-latest'
      - uses: Swatinem/rust-cache@v2
      - name: Install Dependencies (Ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev \
            build-essential \
            curl \
            wget \
            libgtk-3-dev \
            libayatana-appindicator3-dev \
            librsvg2-dev
      - name: Cache Pnpm Modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: release-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            release-${{ runner.os }}-
      - uses: pnpm/action-setup@v2
        name: Install App Dependencies
        with:
          version: latest
          run_install: true
      - uses: tauri-apps/tauri-action@dev
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ENABLE_CODE_SIGNING: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE: ${{ secrets.APPLE_CERTIFICATE }}
          APPLE_CERTIFICATE_PASSWORD: ${{ secrets.APPLE_CERTIFICATE_PASSWORD }}
          APPLE_SIGNING_IDENTITY: ${{ secrets.APPLE_SIGNING_IDENTITY }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_PASSWORD: ${{ secrets.APPLE_PASSWORD }}
        with:
          tagName: 'shuiyuan-archiver/v__VERSION__'
          releaseName: 'shuiyuan-archiver/v__VERSION__'
          releaseBody: ''
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.platform == 'macos-latest' && '-v --target universal-apple-darwin' || '-v' }}
